### ISSUE TITLE
Doesn't compile with GCC (MinGW 4.8.1)

### ISSUE THREAD

**Issue by coderalpha** [hicknhack-software/QSqlMigrator#12]
I tried to compile master with various errors and then tried the released version 1.0, with the following error.
The class column contains a private const member variable:

```
const Attributes m_attributes;
```

which result in the following error:

```
C:\Temp\QSqlMigrator-1.0\src\Structure\Column.h:40: error: non-static const member 'const Attributes Structure::Column::m_attributes', can't use default assignment operator
 class QSQLMIGRATOR_DLL_EXPORT Column
```
